"""Collect all separation values generated by gen_separation_distr.py"""

from pathlib import Path

import numpy as np

from supermops.utils.utils import *

root = Path(".")
seps = []
for sepf in root.glob("sep_*_*.npy"):
    print(sepf)
    seps += np.load(sepf).tolist()
print(f"Collected {len(seps)} seps")
announce_save("separations", seps)